version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: school-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: schooldb
      MYSQL_USER: schooluser
      MYSQL_PASSWORD: schoolpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - school-net

  backend:
    image: bilaljugg796/school-app-backend:latest
    container_name: school-backend
    restart: always
    ports:
      - "3500:3500"
    depends_on:
      - db
    networks:
      - school-net

  frontend:
    image: bilaljugg796/school-app-frontend:latest
    container_name: school-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - school-net

volumes:
  db_data:

networks:
  school-net:
